/** Portuguese labels and search aliases per icon — used for suggestions and picker tooltips. */
export const ICON_ALIASES = {
  target: ["meta", "objetivo", "goal", "alvo"],
  star: ["estrela", "sonho", "aspiração", "aspiracao", "wishlist"],
  house: ["casa", "imóvel", "imovel", "apartamento", "moradia", "aluguel", "condomínio", "condominio", "iptu"],
  home: ["lar", "residência", "residencia"],
  car: ["carro", "veículo", "veiculo", "automóvel", "automovel", "suv", "hatch"],
  motorcycle: ["moto", "motocicleta", "motociclo"],
  bicycle: ["bicicleta", "bike", "ciclismo"],
  plane: ["viagem", "travel", "passagem", "hotel", "férias", "ferias", "turismo", "aéreo", "aereo"],
  baby: ["bebê", "bebe", "filho", "filha", "filhos", "maternidade", "enxoval"],
  paw: ["pet", "cachorro", "gato", "animal", "veterinário", "veterinario"],
  ring: ["casamento", "noivado", "aliança", "alianca", "wedding"],
  dumbbell: ["academia", "fitness", "treino", "gym", "exercício", "exercicio", "musculação", "musculacao"],
  smartphone: ["celular", "telefone", "iphone", "android", "eletrônico", "eletronico", "gadget"],
  gift: ["presente", "gift", "aniversário", "aniversario"],
  food: ["comida", "mercado", "supermercado", "restaurante", "alimentação", "alimentacao", "ifood", "lanche", "padaria"],
  transport: ["transporte", "uber", "99", "taxi", "táxi", "ônibus", "onibus", "metrô", "metro"],
  fuel: ["combustível", "combustivel", "gasolina", "etanol", "posto", "abastecer"],
  parking: ["estacionamento", "zona azul", "garagem"],
  health: ["saúde", "saude", "médico", "medico", "hospital", "farmácia", "farmacia", "plano de saúde", "dentista", "exame"],
  education: ["educação", "educacao", "curso", "faculdade", "escola", "universidade", "matrícula", "matricula", "livro", "mba"],
  subscription: ["assinatura", "netflix", "spotify", "streaming", "amazon prime", "disney", "hbo", "mensalidade"],
  shopping: ["compras", "shopping", "loja", "roupa", "vestuário", "vestuario", "amazon", "shein"],
  salary: ["salário", "salario", "salary", "prolabore", "pró-labore", "pro labore", "holerite", "pagamento", "freela", "freelance"],
  bill: ["conta", "boleto", "fatura", "luz", "água", "agua", "gás", "gas", "internet", "telefone"],
  loan: ["financiamento", "empréstimo", "emprestimo", "parcela", "prestação", "prestacao", "juros"],
  invest: ["invest", "investimento", "ações", "acoes", "ação", "acao", "etf", "fii", "bolsa", "carteira", "cdb", "tesouro"],
  piggyBank: ["poupança", "poupanca", "aposentadoria", "fire", "independência", "independencia", "reserva", "guardar"],
  shield: ["emergência", "emergencia", "reserva de emergência", "seguro", "proteção", "protecao"],
  bank: ["banco", "conta bancária", "conta bancaria", "nubank", "inter", "itau", "bradesco"],
  wallet: ["carteira", "dinheiro", "bolso"],
  creditCard: ["cartão", "cartao", "crédito", "credito", "fatura do cartão"],
  cash: ["dinheiro", "espécie", "especie", "saque"],
  coins: ["moedas", "troco", "renda extra", "extra"],
  percent: ["imposto", "tax", "irpf", "das", "tributo", "iss", "inss", "fgts"],
  building: ["empresa", "negócio", "negocio", "pj", "cnpj", "escritório", "escritorio", "business"],
  exchange: ["câmbio", "cambio", "dólar", "dolar", "euro", "remessa", "wise"],
  transfer: ["transferência", "transferencia", "pix", "ted", "doc"],
  receipt: ["recibo", "nota fiscal", "comprovante"],
  repeat: ["recorrente", "mensal", "fixo", "assinatura fixa"],
  repair: ["conserto", "manutenção", "manutencao", "reparo"],
  bitcoin: ["bitcoin", "btc", "cripto", "crypto", "ethereum", "eth"],
  atm: ["caixa eletrônico", "caixa eletronico", "saque"],
  tag: ["outros", "geral", "diversos", "misc"],
} as const;

export type IconAliasKey = keyof typeof ICON_ALIASES;

export const ICON_LABELS: Record<IconAliasKey, string> = {
  target: "Meta",
  star: "Sonho",
  house: "Casa / imóvel",
  home: "Lar",
  car: "Carro",
  motorcycle: "Moto",
  bicycle: "Bicicleta",
  plane: "Viagem",
  baby: "Bebê / família",
  paw: "Pet",
  ring: "Casamento",
  dumbbell: "Academia",
  smartphone: "Celular",
  gift: "Presente",
  food: "Alimentação",
  transport: "Transporte",
  fuel: "Combustível",
  parking: "Estacionamento",
  health: "Saúde",
  education: "Educação",
  subscription: "Assinatura",
  shopping: "Compras",
  salary: "Salário",
  bill: "Conta / boleto",
  loan: "Financiamento",
  invest: "Investimento",
  piggyBank: "Poupança / FIRE",
  shield: "Emergência",
  bank: "Banco",
  wallet: "Carteira",
  creditCard: "Cartão",
  cash: "Dinheiro",
  coins: "Moedas",
  percent: "Impostos",
  building: "Empresa / PJ",
  exchange: "Câmbio",
  transfer: "Transferência",
  receipt: "Recibo",
  repeat: "Recorrente",
  repair: "Manutenção",
  bitcoin: "Cripto",
  atm: "Caixa",
  tag: "Outros",
};
